### ISSUE TITLE
Don't register collective.js.cycle2 resources

### ISSUE THREAD

**Issue by hvelarde** [simplesconsultoria/sc.photogallery#10]
This package use resources from [collective.js.cycle2](https://github.com/collective/collective.js.cycle2) for the slideshow and the tile. If we register the resources in the JS registry we could fall into the following issue:

* install this package and register the resources
* install another package, like [collective.nitf](https://github.com/collective/collective.nitf), that use the same approach and also register the resources
* uninstall this package

Now the second package is broken because the resources were removed from the registry.
like this:
To avoid that we should provide in all packages an alternative way of using the resources:

* let the job of registering the resources into the JS registry to a policy package
* all views that need to load resources from collective.js.cycle2 should look first into the registry: if the resources are there, do nothing; if the resources are not there, load them

We could use something lime this:

```python
def resources_available():
    # Check if all resources are available via portal_javascripts.getResourceIds()
```

```xml
<head tal:condition="not:view/resources_available">
  <script tal:attributes="src string:${portal_url}/++resource++collective.js.cycle2/jquery.cycle2.min.js"></script>
  <script tal:attributes="src string:${portal_url}/++resource++collective.js.cycle2/jquery.cycle2.carousel.min.js"></script>
  <script tal:attributes="src string:${portal_url}/++resource++collective.js.cycle2/jquery.cycle2.swipe.min.js"></script>
  <script tal:attributes="src string:${portal_url}/++resource++sc.photogallery/photogallery.js"></script>
</head>
```

The above code is for a tile; for normal views, resources have to be inserted in the ``javascript_head_slot``.

**Comment by hvelarde** [comment]
@rodfersou @djowett comments? we should use the same approach on [covertile.cycle2](https://github.com/collective/covertile.cycle2) and collective.nitf.

**Comment by djowett** [comment]
Hi, good point.  But the solution is such an overhead in template coding.... this makes me want the profile back in collective.js.cycle2 for at least the main JS file.

OR - you could take a look at [plone.app.jqueryui](https://github.com/plone/plone.app.jqueryui) for inspiration....

**Comment by hvelarde** [comment]
@djowett registering one JS only doesn't solve the problem as you will have to load the plugins as well; on the other side, I'm open open to find other solutions but, IMO, I found the one on plone.app.jqueryui pretty complicated.

I need to cut a release; we can think on options later.

**Comment by djowett** [comment]
You're right on both points, and you better get your release done.

But in the long term - I believe this highlights a major problem in [collective.js.cycle2](https://github.com/collective/collective.js.cycle2) - basically that package is IMO *literally* causing as many problems as it solves, which is unpythonic (remember [antigravity](http://xkcd.com/353/)?)...  it is simpler to just stick the JS I need in a static folder of covertile.cycle2 (or sc.photogallery)

**Comment by hvelarde** [comment]
we will still have the same problem; for instance, I have now a font page that uses a slideshow tile from sc.photogallery, another from covertile.cycle2 and a third one from the project itself.

how do I solve that? :-)
