### ISSUE TITLE
Update README and setup.py to Plone5

### ISSUE THREAD

**Issue by svx** [simplesconsultoria/sc.photogallery#31]
The README is not updated according to the Changelog :)

Changelog:
```
1.0b1 (2016-03-15)
------------------

- Remove hard dependency on plone.app.referenceablebehavior as Archetypes is no longer the default framework in Plone 5.
  Under Plone < 5.0 you should now explicitly add it to the `eggs` part of your buildout configuration to avoid issues while upgrading.
  [hvelarde]
```
This is mentioned on PyPi, because Changes.rst is fetched, but if you are lookingt on GitHub, it is not clear that this product is working with Plone 5, IMHO, the install part of the README should be updated to cover both Plone versions ? :)

Maybe it would be also nice to update setup.py and add there:
```
'Framework :: Plone :: 5.0'
```
:)

**Comment by hvelarde** [comment]
@svx this product is still not compatible with Plone 5 as stated in the classifiers; that changelog entry just mentions an step made in search of such compatibility.

**Comment by svx** [comment]
OK, sorry than, at least for me your changelog is confusing :) 

Ah well maybe its a language thing :)

**Comment by hvelarde** [comment]
sorry about that; I though the same thing when I was reviewing it to make the release, but I always use explicitly something like _Package is now compatble with Plone x.y_.
